### PR TITLE
Adding Ukrainian to the list of languages

### PR DESCRIPTION
**Pull request by Borales**

### CODE REVIEW

**Comment by norzechowicz** [comment]
@Borales could you please 

1. rebase your branch against master
2. check if you can translate also https://github.com/coduo/php-humanizer/blob/master/src/Coduo/PHPHumanizer/Resources/translations/oxford.en.yml 
3. add tests in
     [DateTimeTest](https://github.com/coduo/php-humanizer/blob/master/tests/Coduo/PHPHumanizer/Tests/DateTimeTest.php) and 
    [CollectionTest](https://github.com/coduo/php-humanizer/blob/master/tests/Coduo/PHPHumanizer/Tests/CollectionTest.php)
(execute them by ``bin/phpunit``) 

:P

**Comment by Borales** [comment]
dobrze :)

**Comment by Borales** [comment]
@norzechowicz ready

**Comment by norzechowicz** [comment]
@Borales awesome! Thanks! :beers:

**Pull request merged**
