### PR TITLE
Add Czech locale

### PR DESCRIPTION
**Pull request by tomasfejfar**
I added the `cs` locale to the list. Unfortunately there is a problem with missing functionality as described in last commit (b92c0e7f77985ff8652c51147c0b9b96e61cbabf). Practically past and future version of precise time differ in Czech and there does not seem to be an option to specify it. Most of the functionality works well though as seen in tests. 

It's up to you to either merge it with the small issue or keep it open for someone to add the missing functionality to code.

### CODE REVIEW

**Comment by norzechowicz** [comment]
Thanks for this PR, please give me some time I'll try to figure out a way to handle scenario that you desceibed

**Comment by tomasfejfar** [comment]
You're welcome :) Let me know if you need anything.

**Comment by rapemer** [comment]
@norzechowicz ping ...

**Comment by norzechowicz** [comment]
If we could rebase it

**Pull request closed without merging**
