### PR TITLE
Translations for es_ES

### PR DESCRIPTION
**Pull request by juanramirez**
Added translations for es_ES (Spanish castilian)

### CODE REVIEW

**Comment by norzechowicz** [comment]
@juanramirez thanks! Could you please rebase your branch against current master? There are some conflicts right now.

**Comment by juanramirez** [comment]
Of course, I already saw it.
I also added translations for collections :)

**Comment by norzechowicz** [comment]
@juanramirez thanks! Can you also please take a look at https://github.com/coduo/php-humanizer/pull/26 ? There was a problem with missing suffix in translation keys, do you think es_ES locale has similar problem or maybe current translations make perfect sense?

**Comment by juanramirez** [comment]
Well, I also though on it, current ones make sense but they don't feel very natural.
I wanted to translate date differences by something like "hace X segundos" (for the past) and "en X segundos" (for the future), and I realized I couldn't.
I'll take a look.

**Comment by norzechowicz** [comment]
Yea I think @Forst is workin on possibility to use prefix/suffix when required. Also #41 already have implementation for that but still need some tests.

**Comment by juanramirez** [comment]
Added this pull request for branch in #41, with the tests for PreciseFormatter:
https://github.com/sam002/php-humanizer/pull/1

**Comment by juanramirez** [comment]
I'll fix this once #41 is merged :)

**Comment by orestes** [comment]
This PR is duplication of #26. I started with the Spanish translations there and pointed a few things that should be improved. I was supposed to wait for #23, but that was closed and the work continued on #41, so I'm waiting for it.

**Comment by norzechowicz** [comment]
#41 was merged

**Comment by juanramirez** [comment]
Hi, @orestes. I didn't see your PR when I did this one. I'm happy with either updating this PR or you updating yours :)

**Comment by orestes** [comment]
@norzechowicz it was merged shortly after I commented. Up until then, I had been waiting for it like you asked me to.
@juanramirez no problem. Already updated #26.

**Comment by norzechowicz** [comment]
Closed by #26

**Pull request closed without merging**
