### PR TITLE
Disable xdebug for Travis CI

### PR DESCRIPTION
**Pull request by blazarecki**
Speed up test by removing xdebug extension

### CODE REVIEW

**Comment by norzechowicz** [comment]
why?

**Comment by blazarecki** [comment]
In order to speed up test.

screen shot 2016-01-19 at 14 26 36
screen shot 2016-01-19 at 14 26 44

**Comment by norzechowicz** [comment]
And u are sure that this differene came out from removing xdebug? I'm not so sure about that to be honest, maybe u can you prove it somehow?

**Comment by norzechowicz** [comment]
Closed because lack of proofs that it will give us extra speed.

**Pull request closed without merging**
