### PR TITLE
Addition of Portuguese (pt) language translation (with spec tests)

### PR DESCRIPTION
**Pull request by lightglitch**
Hi,

In terms of context of the translations when you have the text:

> %count% seconds from now

you mean the same as:

> in about %count% seconds  

or

> in %count% seconds  

Because the translation of the second sentence makes more sense to me in Portuguese and if it's the same for you I will change the texts.

PS: I'm also getting some errors in the tests for Numbers in my machine but I will look into that later.

### CODE REVIEW

**Comment by norzechowicz** [comment]
@lightglitch thanks a lot!

**Comment by lightglitch** [comment]
@norzechowicz Did you see my doubt in the description?

**Comment by norzechowicz** [comment]
about the ``in %count% seconds`` ?

**Comment by lightglitch** [comment]
Yep.

**Comment by norzechowicz** [comment]
well it depends if this gonna works for all other languages. I see the point for english, for polish also. It would be something like ``za %count% sekund`` but not sure about the others.

**Comment by lightglitch** [comment]
I think that in Portuguese the meaning is more or less the same but the second sounds better, I will update for Portuguese as soon as I can.

**Comment by norzechowicz** [comment]
:+1:

**Pull request merged**
