### PR TITLE
Add Chinese Simplified (zh_CN)

### PR DESCRIPTION
**Pull request by arrowrowe**
Add Chinese Simplified ~~(zh_CHS)~~ (zh_CN).

~~BTW, I changed the regex in `Coduo\PHPHumanizer\Translator\Builder` cause 'CHS' has a length of 3.~~ (Since changed to zh_CN, no need to modify this regex now.)

Some trailing spaces removed, some ending blank lines added. (They are done by [Atom](https://atom.io/) automatically...)

### CODE REVIEW

**Comment by norzechowicz** [comment]
@arrowrowe thanks! Could you also add translations for following file https://github.com/coduo/php-humanizer/blob/master/src/Coduo/PHPHumanizer/Resources/translations/oxford.en.yml ?

**Comment by arrowrowe** [comment]
re @norzechowicz: oxford added and language short name renamed (now zh_CN).

**Comment by norzechowicz** [comment]
@arrowrowe thank you very much! :+1:

**Comment by arrowrowe** [comment]
@norzechowicz my pleasure :smile:

**Pull request merged**
