### PR TITLE
localize ordinal number

### PR DESCRIPTION
**Pull request by isnani**

### CODE REVIEW

**Comment by norzechowicz** [comment]
@isnani thanks for this PR! 
Unfortunately we can't merge it like that. This change just like current code is violating "open closed principle", it means that we would need to change code of Number/Ordinal.php with each new language. Could you think about more flexible solution? Maybe translations could help here?

**Comment by norzechowicz** [comment]
@isnani please take a look at https://github.com/coduo/php-humanizer/pull/46 this might be useful for you

**Comment by isnani** [comment]
@norzechowicz I've tried to find a more flexible way of handling ordinal format.
I assumed that the format from any locales can be handled by regular expression. This might not be a good solution though. We will see.

**Comment by martinbutt** [comment]
Any idea on the progress of this PR? I want to add ordinal support for PFIGS languages. Let me know whether you'd prefer I implement them using this method or by implementing a Strategy for each.

**Comment by isnani** [comment]
@martinbutt , I just realized that there exists a strategy written to implement this. Nevertheless, IMHO it needs improvement to handle a language that has ordinal as prefix, e.g Indonesian, Chinese, ...
I will close this PR since it is no longer necessary.

**Pull request closed without merging**
