### PR TITLE
Remove composer.phar file

### PR DESCRIPTION
**Pull request by vinkla**
This file shouldn't be added to the repository.

### CODE REVIEW

**Comment by norzechowicz** [comment]
Could you also add ``composer.phar`` into ``.gitignore``?

**Comment by vinkla** [comment]
I would suggest against that. Since the `composer.phar` file shouldn't exists within the repository in the first place. Better would be to add it to the global ignore file if it is required to use within the repo.

**Comment by norzechowicz** [comment]
This file is here only because we forgot to mention it in ``.gitignore``. It should be added to .gitignore and remove from repo.

**Comment by vinkla** [comment]
No, we don't need to add it to the ignore file. Since it shouldn't be there in the first place.

**Comment by vinkla** [comment]
:+1:

**Comment by norzechowicz** [comment]
Its easier to add this file to .gitignore rather than force everyone to update their global .gitignores. Many php open source projects have this file listed in .gitignore and I see no reason why php-humanizer should not have it. I merged this PR manualy adding composer.phar into .gitignore. 
Thanks for your contribution.

**Pull request merged**
