### PR TITLE
Fix typo in french translation

### PR DESCRIPTION
**Pull request by mattallty**
The right expression is "il y a", not "il y'a"

### CODE REVIEW

**Comment by norzechowicz** [comment]
@mattallty thanks but unfortunately I dont understand french enough to confirm that, @David-Guillot could you please help me here? :P

**Comment by mattallty** [comment]
I *do* speak french, that's why I help...

**Comment by norzechowicz** [comment]
@mattallty of course and Im quite sure u are right here, but the guy who added this translation also looks like a french speaking person thats why I would like to have third opinion here, hope thats not a problem for you. 
Could you please fix spec also?

**Comment by David-Guillot** [comment]
Hi @norzechowicz , I confirm that @mattallty's fix is the correct French expression :)

**Comment by mattallty** [comment]
@norzechowicz no problem :) Spec fixed !

**Comment by norzechowicz** [comment]
Thanks @mattallty and @David-Guillot!

**Pull request merged**
