### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by vinkla**
Added `preferred-install`, `minimum-stability` and `prefer-stable` parameters.

### CODE REVIEW

**Comment by norzechowicz** [comment]
And could you explain how those changes improved php-humanizer?

**Comment by vinkla** [comment]
- preferred-install - This can speed up installs substantially on build servers and other use cases where you typically do not run updates of the vendors. It is also a way to circumvent problems with git if you do not have a proper setup.

- minimum-stability - https://getcomposer.org/doc/04-schema.md#minimum-stability

- prefer-stable - https://getcomposer.org/doc/04-schema.md#prefer-stable

**Comment by norzechowicz** [comment]
``preferred-install`` this could be added  to ``.travis.yml`` as a ``--prefer-dist`` 

I know what those parameters are. I just dont see any valid reason to have them and sice u added them please explain my why do we need them. Are you solving any problem or just adding them cuz you seen that somewhere else?

**Comment by vinkla** [comment]
I've closed all my pull-requests for this repository now. I don't see the point of trying to help out making this repository better. I'm only trying to push for better and new standards. Thanks anyway.

**Comment by norzechowicz** [comment]
lol if you can't explain reason behind changes that you have done how you could expect somebody gonna merge them?

**Comment by vinkla** [comment]
https://github.com/coduo/php-humanizer/pull/56#issuecomment-155360614 https://github.com/coduo/php-humanizer/pull/57#issuecomment-155360815

**Comment by magnus-bergman** [comment]
Nice attitude towards people trying to help out. This pull request makes the repository follow composer guidelines for better packages. It doesn't add any overhead to the package or makes it worse in any way. What is your argument for not merging it?

**Comment by norzechowicz** [comment]
And what are arguments for merging it?

**Comment by magnus-bergman** [comment]
The arguments are specified in the previous comments? As @vinkla pointed out in his last comment. I would like to hear your reason now.

**Comment by norzechowicz** [comment]
Ok, so how exactly setting minimum stability for "dev" from "stable" gonna help this library? Is it gonna help in development? Is there any issue with current stability this change gonna solve? 
And why would you like to set "prefer-stable" into true when you just removed requirement from using stable dependencies? Where exactly are those "guidelines for better packages" that you mentioned? 
About ``preferred-install`` I agree about using it for build server, thats why I suggest to move it into .travis.yml.

**Comment by norzechowicz** [comment]
ohh @magnus-bergman about arguments, please show me where excatly in this conversation @vinkla answered my question "why do we need those changes?".

**Comment by vinkla** [comment]
In this case we might only need to add `preferred-install`. Closing this isn't just related to this pull request. My other pull requests would make this package better.

**Comment by vinkla** [comment]
Since the package is broken `minimum-stability` would also be good to add.

**Comment by vinkla** [comment]
As well as `prefer-stable` since we prefer it over `unstable`.

**Comment by norzechowicz** [comment]
@vinkla but adding ``minimum-stability`` is ``stable`` by default - please read docs that you posted here. Why would you like to change it? 
And if you dont change ``minimum-stability`` then there is no need to set up ``prefer-stable`` because only ``stable`` dependencies gonna be used.

**Comment by vinkla** [comment]
I want to change it to `dev` not `stable`.

**Comment by norzechowicz** [comment]
I know, but what I dont know is why?

**Comment by vinkla** [comment]
https://github.com/coduo/php-humanizer/pull/57#issuecomment-155360815

**Comment by norzechowicz** [comment]
I still dont see how setting minimum stability into dev gonna help...

**Comment by vinkla** [comment]
Lets just drop it. We can agree to disagree.

**Comment by norzechowicz** [comment]
Agree, if you can't explain why would you like to change minimum stability from stable into dev there is no point in continuing this conversation.

**Pull request closed without merging**
